

-- MASKING POLICY

//SWITCH ROLE
USE ROLE SYSADMIN;

//CREATE MASKING POLICY
CREATE OR REPLACE MASKING POLICY EMAIL_MASK AS (VAL STRING) RETURN STRING ->
CASE
	WHEN CURRENT_ROLE() <> ('SENSITIVE_ALLOWED_ROLE') THEN 'XXX-XX-XXXX'
	ELSE VAL
END;


//ATTACH THE MASKING POLICY TO THE CUSTOMER_EMAIL COLUMN ON THE NORMAL VIEW, WE CREATED EARLIER 
ALTER VIEW PRESENTATION.CUSTOMER_LAST_ORDER_DATE MODIFY COLUMN CUSTOMER_EMAIL SET MASKING POLICY EMAIL_MASK;





//CHANGE THE CONTEXT OF THE ROLE AND OBSERVE RESULTS
USE ROLE SENSITIVE_ALLOWED_ROLE;
SELECT * FROM PRESENTATION.CUSTOMER_LAST_ORDER_DATE;


USE ROLE SENSITIVE_ALLOWED_ROLE;
SELECT * FROM PRESENTATION.CUSTOMER_LAST_ORDER_DATE;


//WHAT WILL THE DDL LOOK LIKE?
SELECT GET_DDL('VIEW', 'PRESENTATION.CUSTOMER_LAST_ORDER_DATE', TRUE);



