
-- set the DATABASE
USE SCHEMA SCHEMACHANGE_DEMO.PUBLIC;

COPY INTO TRIPS FROM @TRIPS
	FILE_FORMAT = (FORMAT_NAME = 'CSV_NO_HEADER');

--
COPY INTO WEATHER FROM
	(
		SELECT 
			$1
			,CONVERT_TIMEZONE('UIC', 'US/Eastern', $1:time::TIMESTAMP_NTZ)
		FROM @WEATHER
	)
	FILE_FORMAT = (FORMAT_NAME = 'JSON');





