

USE SCHEMA (( DB )).(( SCH ));

CREATE TABLE DEPARTMENT (
	ID NUMBER(38) NOT NULL,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	ACTIVE BOOLEAN DEFAULT TRUE,
	CONSTRAINT PK-DEPARTMENT PRIMARYKEY (ID));


